apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: umami
  name: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  strategy: {}
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - image: ghcr.io/umami-software/umami:postgresql-latest@sha256:fa32d116cf20cad52cbc3fad9a63b46e7fa02299d8f967168eb453d49c476b4a
          name: umami
          ports:
            - containerPort: 3000
          resources: {}
          env:
            - name: DATABASE_TYPE
              value: postgresql
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami-pg-app
                  key: uri
            - name: HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: umami-secrets
                  key: hash-salt
