apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: umami
  name: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  strategy: {}
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
        - image: ghcr.io/umami-software/umami
          name: umami
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 300m
            limits:
              memory: 1Gi
              cpu: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: DATABASE_TYPE
              value: postgresql
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: umami-pg-app
                  key: uri
            - name: HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: umami-secrets
                  key: hash-salt
          livenessProbe:
            httpGet:
              path: /api/heartbeat
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
