resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./secret.yaml

images:
  - name: ghcr.io/umami-software/umami
    newTag: 3.3.1@sha256:fa32d116cf20cad52cbc3fad9a63b46e7fa02299d8f967168eb453d49c476b4a
