resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./secret.yaml

images:
  - name: ghcr.io/umami-software/umami
    newTag: 3.4.0@sha256:85909afc45bdcda1917394594a087421fdbb05610fded0fa9f6fb861abb2f367
