# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-agent
  labels:
    app: hermes-agent
spec:
  selector:
    matchLabels:
      app: hermes-agent
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  hermes-agent
      labels:
        app: hermes-agent
    spec:
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
        runAsGroup: 10000
        runAsNonRoot: true
      initContainers:
      - name: init-container-mode
        image: busybox
        command: ["sh", "-c", "mkdir -p /opt/data && touch /opt/data/.container-mode && chown -R 10000:10000 /opt/data"]
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
      containers:
      - name: hermes-agent
        image: nousresearch/hermes-agent
        args: [gateway, run]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        envFrom:
          - secretRef:
              name: hermes-secrets
          - configMapRef:
              name: hermes-configmap-1
        ports:
        - containerPort: 8642
          name: hermes-agent
        volumeMounts:
        - name: data
          mountPath: /opt/data
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hermes
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---

