resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./secret.yaml
  - ./secret-bootstrap.yaml

images:
  - name: nousresearch/hermes-agent
    newTag: v2026.9.24@sha256:fca358f12efd65bfaaca05884166f15c0e2788375ca30d77061ac1ebc96452b7

configMapGenerator:
  - name: hermes-configmap-1
    envs:
      - ./env_config
  - name: hermes-config-file
    files:
      - config.yaml=./hermes-config.yaml
