resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./secret.yaml
  - ./secret-bootstrap.yaml

images:
  - name: nousresearch/hermes-agent
    newTag: v2026.8.3@sha256:16788311e2fa3035456bdc1bafb8ec2b1777db64ebf020af9bb7eb73c3712c9e

configMapGenerator:
  - name: hermes-configmap-1
    envs:
      - ./configmap.yaml
  - name: hermes-config-file
    files:
      - config.yaml=./hermes-config.yaml
