resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./secret.yaml
  - ./secret-bootstrap.yaml

images:
  - name: nousresearch/hermes-agent
    newTag: latest@sha256:f1b8c07ef0eaa6a518a03bbb8e66a75a6c129ee96ce8efe244bc1a38b1ad191a

configMapGenerator:
  - name: hermes-configmap-1
    envs:
      - ./configmap.yaml
  - name: hermes-config-file
    files:
      - config.yaml=./hermes-config.yaml
