apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-helpers
  namespace: argocd
spec:
  project: default
  source:
    path: /awx/templates/
    repoURL: 'https://github.com/smiggiddy/argo'
    targetRevision: HEAD

  destination:
    server: https://pxmx-awx01:6443
    namespace: awx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
