apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://ansible.github.io/awx-operator/
    targetRevision: 2.19.0
    chart: awx-operator

    helm:
      values: |
        AWX:
          enabled: true
          spec:
            admin_user: smig
            ingress_type: ingress 
            ingress_hosts:
              - hostname: awx.lab.smig.tech 
                tls_secret: awx-secret-tls 
            auto_upgrade: true 
            task_replicas: 2 
            admin_password_secret: awx-admin
            task_resource_requirements:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 2000m
                memory: 4Gi
            ee_resource_requirements:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 1000m
                memory: 4Gi
            web_resource_requirements:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 1Gi
          server:
            dataStorage:
              storageClass: nfs-client


  destination:
    server: https://pxmx-awx01:6443
    namespace: awx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
