apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://ansible.github.io/awx-operator/
    targetRevision: 2.19.0
    chart: awx-operator

    helm:
      parameters:
        - name: server.dataStorage.storageClass
          value: nfs-client
        - name: AWX.spec.admin_user
          value: smig
        - name: AWX.enabled
          value: "true"
        - name:  AWX.spec.ingress_type
          value: ingress 
        - name: AWX.spec.ingress_hosts[0].hostname
          value: awx.lab.smig.tech 
        - name: AWX.spec.ingress_hosts[0].tls_secret
          value: awx-secret-tls
        - name: AWX.spec.auto_upgrade
          value: "true"
        - name: AWX.spec.task_replicas
          value: "2"
        - name: AWX.spec.admin_password_secret
          value: "awx-admin"


  destination:
    server: https://pxmx-awx01:6443
    namespace: awx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
