apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-pg
  namespace: cnpg-system
spec:
  namespaceSelector:
    matchNames:
      - authentik
  selector:
    matchLabels:
      cnpg.io/cluster: authentik-pg
  podMetricsEndpoints:
    - port: metrics
