apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  instances: 3
  storage:
    size: 4Gi
  resources:
    requests:
      memory: "384Mi"
      cpu: "1000m"
    limits:
      memory: "384Mi"
      cpu: "1000m"
  # bootstrap:
  #   initdb:
  #     database: authentik
  #     owner: authentik
  #     encoding: UTF8
  #     localeCType: C
  #     localeCollate: C
  #     secret:
  #       name: authentik-postgres-credentials

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-pg
