apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: cnpg-system
spec:
  instances: 3
  storage:
    size: 4Gi
  resources:
    requests:
      memory: "384Mi"
      cpu: "500m"
    limits:
      memory: "384Mi"
      cpu: "500m"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-pg
