apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  instances: 3
  storage:
    size: 4Gi
  resources:
    requests:
      memory: "384Mi"
      cpu: "500m"
    limits:
      memory: "384Mi"
      cpu: "500m"

  bootstrap:
    recovery:
      source: authentik-pg

  externalClusters:
    - name: authentik-pg
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: authentik-pg

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-pg
