apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
  namespace: immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18-1.1.1@sha256:c7672bc011351a587cc292a94aac7eeebb593ed2e120077bd9c9944c9467db93
  instances: 1
  enableSuperuserAccess: true

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  managed:
    roles:
      - name: immich
        ensure: present
        superuser: true
        login: true
        inherit: true
        connectionLimit: -1

  storage:
    size: 8Gi
    storageClass: longhorn
    resizeInUseVolumes: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      encoding: UTF8
      localeCType: C
      localeCollate: C
      secret:
        name: immich-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
        - alter role immich set search_path TO "$user", public;

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-pg
