resources:
  - ./nextcloud-cnpg-cluster.yaml
  - ./nextcloud-backup-secret.yaml
  - ./nextcloud-cnpg-backup.yaml
  - ./nextcloud-db-secret.yaml
  - ./authentik-pg.yaml
  - ./authentik-objectstore.yaml
  - ./authentik-r2.yaml
  - ./authentik-secret.yaml
  - ./authentik-backup-secret.yaml
  - ./authentik-cnpg-backup.yaml
  - ./authentik-podmonitor.yaml
  - ./open-webui-cnpg.yaml
