apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: pgvector
spec:
  images:
    - major: 17
      image: pgvector/pgvector:pg17@sha256:d2ef61f42ef767baa5a1475393303cc235bcd92febd9d7014eddb48b41f3bad0
