apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: pgvector
spec:
  images:
    - major: 17
      image: pgvector/pgvector:pg17@sha256:7ae6051efd0e60444282c27c7e141af07f322ce033300e727a49c3dd11075e38
