apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: pgvector
spec:
  images:
    - major: 17
      image: pgvector/pgvector:pg17@sha256:cf134a767f474095eeba57e0117be8e568e011a63f33fbf252f14c9b760f8e6f
