apiVersion: v1
stringData:
  username: the_method
  password: <password>
kind: Secret
metadata:
  name: the-method-postgres-credentials
  namespace: smigz
  annotations:
    avp.kubernetes.io/path: "k8s/data/argocd/the-method"
type: kubernetes.io/basic-auth
