apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        resources:
          requests:
            cpu: 100m
            memory: "64Mi"
          limits:
            cpu: 150m
            memory: "128Mi"
