apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    apps: utilities 
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
    #server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.1
    chart: longhorn

    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_values
          value: |
            test: <path:k8s/data/argocd/test#ingress>

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
--- 

                - name: avp-helm
                  command: 
                    - /var/run/argocd/argocd-cmp-server
                  image: registry.access.redhat.com/ubi8
                  securityContext:
                    runAsNonRoot: true
                    runAsUser: 999
                  volumeMounts:
                    - mountPath: /var/run/argocd
                      name: var-files
                    - mountPath: /home/argocd/cmp-server/plugins
                      name: plugins
                    - mountPath: /tmp
                      name: tmp
                    - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                      subPath: argocd-vault-plugin-helm.yaml
                      name: cmp-plugin
                    - name: custom-tools
                      subPath: argocd-vault-plugin
                      mountPath: /usr/local/bin/argocd-vault-plugin  


---
                  argocd-vault-plugin-helm:
                    allowConcurrency: true
                    discover:
                      find:
                        command:
                          - sh
                          - "-c"
                          - "find . -name 'Chart.yaml' && find . -name 'values.yaml'"
                    generate:
                      command:
                        - bash
                        - "-c"
                        - |
                          helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f <(echo "$ARGOCD_ENV_helm_values") . |
                          argocd-vault-plugin generate -
                    lockRepo: false