apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bentopdf
  name: bentopdf
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bentopdf
  strategy: {}
  template:
    metadata:
      labels:
        app: bentopdf
    spec:
      containers:
        - image: ghcr.io/alam00000/bentopdf:2.8.6@sha256:eaeea1e447205a79cb61d7efdc6966f37311dc1bc9c36a3a5c897bf79107c2c3
          name: bentopdf
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
