resources:
  - deployment.yaml
  - service.yaml
  - service-homekit.yaml
  - ingress.yaml
  - ingressroute-tcp.yaml
  - udproute.yaml
  - service-mdns.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: stable@sha256:3e2dff545c46e91f4ab2b21597016011d76d0de58bc8eaf51d75e841f337bf88

configMapGenerator:
  - name: home-assistant-config
    behavior: create
    envs:
      - config.env

generatorOptions:
  disableNameSuffixHash: false

commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: home-automation
