resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: stable@sha256:14931c6b13756317849f46da1d01b45937a1150db66c081cfe529d48215943fe

configMapGenerator:
  - name: home-assistant-config
    behavior: create
    envs:
      - config.env

generatorOptions:
  disableNameSuffixHash: false

commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: home-automation
