resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: stable@sha256:ae0800c81fea16bc1241ce03bddb9c6260566e90f58b09d3e5a629e4f68bdc0b

configMapGenerator:
  - name: home-assistant-config
    behavior: create
    envs:
      - config.env

generatorOptions:
  disableNameSuffixHash: false

commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: home-automation
