apiVersion: v1
stringData:
  clientID: <clientID>
  clientSecret: <clientSecret>
kind: Secret
metadata:
  name: gitea-argocd
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "k8s/data/argocd/argocd-gitea"
type: Opaque
