apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-pg
  namespace: nextcloud
spec:
  instances: 1
  storage:
    size: 4Gi

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: nextcloud-pg

