apiVersion: v1
data:
  config.json: <dockerconfig>
kind: Secret
metadata:
  name: cr-smigz-com-registry
  namespace: default
  annotations:
    avp.kubernetes.io/path: "k8s/data/argocd/registry"
type: kubernetes.io/dockerconfigjson
