resources:
  - ./configmap.yaml
  - ./deployment.yaml
  - ./ingress.yaml
  - ./service.yaml

images:
  # original image is image: searxng/searxng:2025.8.1-3d96414@sha256:3f229455cee2e21bd9bd910fd1193687b380ebe2a083e15ad19bd5df72bab47f
  - name: searxng/searxng
    newName: ghcr.io/searxng/searxng
    newTag: 2026.5.15-afafca93f
