resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml

configMapGenerator:
  - name: floci-config
    files:
      - ./floci-config

commonLabels:
  app.kubernetes.io/name: floci
  app.kubernetes.io/part-of: floci
