apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mattermost-cnpg-secret.yaml
  - ./mattermost-db-secret.yaml
  - ./mattermost-object-secret.yaml
  - ./mattermost-cnpg-cluster.yaml
  - ./mattermost-installation.yaml
