apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: git.thecodedom.com/smig
    targetRevision: 0.1.3
    chart: actual

    helm:
      valuesObject:
        persistence:
          existingClaim: "actual-pvc"
        ingress:
          enabled: true
          className: "traefik"
          annotations: 
            cert-manager.io/cluster-issuer: cluster-ca-issuer
          hosts:
            - host: actual.lab.smig.tech
              paths:
                - path: /
                  pathType: Prefix
          tls: 
           - secretName: actual-tls
             hosts:
               - actual.lab.smig.tech

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

