apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: git.thecodedom.com/smig
    targetRevision: 0.1.0
    chart: actual

    helm:
      valuesObject:
        persistence:
          existingClaim: "actual-pvc"

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
