apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    avp.kubernetes.io/ignore: "true"
    {{ include "app.notifications" . | nindent 4 }}
spec:
  {{ include "app.syncPolicy.automated" . | nindent 2 }}

  destination:
    namespace: argo
    server: {{ .Values.spec.destination.server }} 
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm 
      chart: argo-workflows
      targetRevision: 2.0.5
      helm:
        valueFiles:
          - $values/apps-values/argo-workflows.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values
