apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    avp.kubernetes.io/ignore: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true

  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm 
    targetRevision: 9.4.2
    chart: argo-cd
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: 'https://gitea.smigz.com/smiggiddy/argocd-values.git'
    targetRevision: HEAD
    ref: values




