apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    apps: utilities
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm 
    targetRevision: 7.3.11
    chart: argo-cd

    helm:     
      valueFiles:
      - $values/argocd/values.yaml

  - repoURL: 'https://gitea.smigz.com/smiggiddy/argocd-values.git'
    targetRevision: HEAD
    ref: values
            
          




