apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    avp.kubernetes.io/ignore: "true"
    {{ include "app.notifications" . | nindent 4 }}
spec:
  {{ include "app.syncPolicy.automated" . | nindent 2 }}

  destination:
    namespace: argo-workflows
    server: {{ .Values.spec.destination.server }} 
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm 
    chart: argo-workflows
    targetRevision: 1.0.6
    helm:
      valuesObject:
        crds:
          full: true
        workflow:
          serviceAccount:
            create: true
            name: "argo-workflow"
          rbac:
            create: true
          workflowNamespaces:
            - default
        server:
          authModes:
            - server
          httproute:
            enabled: true
            parentRefs:
              - name: traefik-gateway
                kind: Gateway
                group: gateway.networking.k8s.io
                namespace: kube-system
                sectionName: websecure
            hostnames:
              - argoworkflows.lab.smig.tech
