apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    apps: utilities
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm 
    targetRevision: HEAD
    targetRevision: 5.29.1 
    chart: argo-cd

    helm:
      parameters:
        - name: configs.params.server.insecure
          value: "true"
        - name: server.ingress.enabled 
          value: "true"
        - name: server.ingress.hosts[0]
          value: "argocd.lab.smig.tech"
        - name: server.ingress.ingressClassName
          value: "traefik"
        
      values: |
          configs:
            params:
              server.insecure: true
            cmp:
              create: yes
              plugins:
                argocd-vault-plugin:
                  allowConcurrency: true
                  discover:
                    find:
                      command:
                        - sh
                        - "-c"
                        - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
                  generate:
                    command:
                      - argocd-vault-plugin
                      - generate
                      - "."
                  lockRepo: false

          server:
            ingress:
              tls:
              - hosts:
                - argocd.lab.smig.tech
                secretName: argocd-tls
          
          repoServer:
            extraContainers: 
              - name: avp
                command: [/var/run/argocd/argocd-cmp-server]
                image: registry.access.redhat.com/ubi8
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 999
                volumeMounts:
                  - mountPath: /var/run/argocd
                    name: var-files
                  - mountPath: /home/argocd/cmp-server/plugins
                    name: plugins
                  - mountPath: /tmp
                    name: tmp
                  - mountPath: /home/argocd/cmp-server/config/plugin.yaml
                    subPath: argocd-vault-plugin.yaml
                    name: cmp-plugin
                  - name: custom-tools
                    subPath: argocd-vault-plugin
                    mountPath: /usr/local/bin/argocd-vault-plugin
            
            initContainers:
              - name: download-tools
                image: registry.access.redhat.com/ubi8
                env:
                  - name: AVP_VERSION
                    value: 1.11.0
                command: [sh, -c]
                args:
                  - >-
                    curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_arm64 -o argocd-vault-plugin &&
                    chmod +x argocd-vault-plugin &&
                    mv argocd-vault-plugin /custom-tools/
                volumeMounts:
                  - mountPath: /custom-tools
                    name: custom-tools

            volumes:
              - configMap:
                  name: argocd-cmp-cm
                name: cmp-plugin
              - name: custom-tools
                  emptyDir: {}

            serviceAccount:
              automountServiceAccountToken: true



