apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    apps: utilities
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm 
    targetRevision: HEAD
    targetRevision: 5.24.0 
    chart: argo-cd

    

