apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    avp.kubernetes.io/ignore: "true"
    {{ include "app.notifications" . | nindent 4 }}
spec:
  {{ include "app.syncPolicy.automated" . | nindent 2 }}

  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }} 
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm 
    targetRevision: 9.5.4
    chart: argo-cd
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: 'https://gitea.smigz.com/smiggiddy/argocd-values.git'
    targetRevision: HEAD
    ref: values




