apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm 
    targetRevision: 9.1.4
    chart: argo-cd

    helm:     
      valueFiles:
      - $values/argocd/values.yaml
      # valuesObject:
    # notifications:
    #   secret:
    #     items:
    #       mattermost-token: <path:k8s/data/argocd/argo-notifications#mattermost-token>

  - repoURL: 'https://gitea.smigz.com/smiggiddy/argocd-values.git'
    targetRevision: HEAD
    ref: values
            
          




