apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    apps: utilities
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm 
    targetRevision: HEAD
    targetRevision: 5.29.1 
    chart: argo-cd

    helm:
      parameters:
        - name: configs.params.server.insecure
          value: "true"
        - name: server.ingress.enabled 
          value: "true"
        - name: server.ingress.hosts[0]
          value: "argocd.lab.smig.tech"
        - name: server.ingress.ingressClassName
          value: "traefik"
        
      values: |
          configs:
            params:
              server.insecure: true
            cmp:
              create: yes
              plugins:
                argocd-vault-plugin:
                  allowConcurrency: true
                  discover:
                    find:
                      command:
                        - sh
                        - "-c"
                        - "find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
                  generate:
                    command:
                      - argocd-vault-plugin
                      - generate
                      - "."
                  lockRepo: false

          server:
            ingress:
              tls:
              - hosts:
                - argocd.lab.smig.tech
                secretName: argocd-tls
          




