apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-redis
  namespace: argocd
  annotations:
    avp.kubernetes.io/ignore: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  project: default
  source:
    repoURL: 'https://github.com/smiggiddy/argo'
    targetRevision: HEAD
    path: ./redis/overlays/authentik


  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
