apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  serviceAccountTemplate:
    metadata:
      name: authentik-cnpg
  storage:
    size: 2Gi
    storageClass: longhorn
