apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  labels:
    apps: authentik 
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2026.2.1
    chart: authentik 
    helm:
      valuesObject:
        authentik:
          secret_key: "<path:k8s/data/argocd/authentik#secret_key>"
          error_reporting:
              enabled: false
          postgresql:
              host: authentik-pg-rw
              user: file:///postgres-creds/username
              password: file:///postgres-creds/password
        redis:
          enabled: false

        server:
            volumes:
              - name: postgres-creds
                secret:
                  secretName: authentik-postgres-credentials
            volumeMounts:
              - name: postgres-creds
                mountPath: /postgres-creds
                readOnly: true
            resources:
              requests:
                cpu: 300m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 768Mi

        worker:
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-postgres-credentials
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true
          resources:
            requests:
              cpu: 300m
              memory: 768Mi
            limits:
              cpu: 1000m
              memory: 1536Mi


  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  {{ include "app.syncPolicy.automated" . | nindent 2 }}






