apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  instances: 3
  storage:
    size: 2Gi
  resources:
    requests:
      memory: "384Mi"
      cpu: "500m"
    limits:
      memory: "384Mi"
      cpu: "500m"

  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: authentik-pg
