apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  labels:
    apps: authentik 
  annotations:
    
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.12.1
    chart: authentik 
    helm:
      valuesObject:
        authentik:
          redis: 
            host: authentik-redis
          secret_key: <k8s/data/argocd/authentik#secret_key>
          error_reporting:
              enabled: false
          postgresql:
              host: authentik-pg-rw
              user: file:///postgres-creds/username
              password: file:///postgres-creds/password
        redis:
          enabled: false

        server:
            volumes:
              - name: postgres-creds
                secret:
                  secretName: authentik-postgres-credentials
            volumeMounts:
              - name: postgres-creds
                mountPath: /postgres-creds
                readOnly: true
            resources:
              requests:
                cpu: 300m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 768Mi

        worker:
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-postgres-credentials
          volumeMounts:
            - name: postgres-creds
              mountPath: /postgres-creds
              readOnly: true
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 768Mi


  destination:
    server: https://kubernetes.default.svc
    namespace: authentik

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true






