apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik
  namespace: authentik
spec:
  bootstrap:
    # initdb:
    #   database: authentik
    #   owner: authentik
    #   secret:
    #     name: authentik-postgres-credentials
    recovery:
      source: source
  storage:
    size: 2Gi
    storageClass: longhorn
  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: authentik
        serverName: authentik
