apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.4 
    chart: cert-manager

    helm:
      values: |
          annotations:
             avp.kubernetes.io/ignore: "true"
      parameters:
        - name: "installCRDs"
          value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: utilities

  syncPolicy:
    syncOptions:
    - CreateNamespace=true