apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1 
    chart: cert-manager

    helm:
      values: |
          crds:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: utilities

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
