apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    avp.kubernetes.io/ignore: "true"
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.20.1 
    chart: cert-manager

    helm:
      values: |
          crds:
            enabled: true
          config:
            enableGatewayAPI: true

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: utilities

  {{ include "app.syncPolicy.automated" . | nindent 2 }}
