apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    avp.kubernetes.io/ignore: "true"
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.21.2 
      chart: cert-manager
      helm:
        valueFiles:
          - $values/apps-values/cert-manager.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: utilities

  {{ include "app.syncPolicy.automated" . | nindent 2 }}
