apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  labels:
    apps: utilities 
    software: database
  # annotations:
  #  avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts 
    targetRevision: 0.25.0
    chart: cloudnative-pg

    # helm:
    #   valuesObject:

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
