apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  labels:
    apps: utilities 
    software: database
  annotations:
    
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
  # annotations:
  #  avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts 
    targetRevision: 0.27.1
    chart: cloudnative-pg

    # helm:
    #   valuesObject:

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
