apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-databases
  namespace: argocd
  labels:
    apps: databases
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: ./kustomizations/cnpg-databases
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
