apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://smiggiddy.github.io
    targetRevision: 3.17.2
    chart: code-server

    helm:     
      values: |
          extraVars:
            - name: CODER_OIDC_ISSUER_URL
              value: "https://auth.thecodedom.com/application/o/code-server/"
            - name: CODER_OIDC_EMAIL_DOMAIN
              value: "gmail.com"
            - name: CODER_OIDC_CLIENT_ID
              value: "<path:k8s/data/argocd/code-server#client_id>"
            - name: CODER_OIDC_CLIENT_SECRET
              value: "<path:k8s/data/argocd/code-server#client_secret>"
            - name: CODER_OIDC_SIGN_IN_TEXT
              value: "Log in with authentic"


          # password: <path:k8s/data/argocd/code-server#password>
          image:
            tag: 'latest'
          persistence: 
            storageClass: longhorn
          ingress:
            enabled: true
            ingressClassName: "traefik"
            annotations: 
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              traefik.ingress.kubernetes.io/router.middlewares: apps-code-server@kubernetescrd
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
            hosts:
            - host: code-server.lab.smig.tech
              paths:
              - /
            tls: 
            - secretName: code-server-tls
              hosts:
              - code-server.lab.smig.tech
