apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  labels:
    apps: utilities
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://smiggiddy.github.io
    targetRevision: 3.17.2
    chart: code-server

    helm:     
      values: |
          extraVars:
            CODER_OIDC_ISSUER_URL: https://auth.thecodedom.com/application/o/code-server/
            CODER_OIDC_EMAIL_DOMAIN: acme.company,acme-corp.company
            CODER_OIDC_CLIENT_ID: <path:k8s/data/argocd/code-server#client_id>
            CODER_OIDC_CLIENT_SECRET: <path:k8s/data/argocd/code-server#client_secret>
            CODER_OIDC_SIGN_IN_TEXT: "Log in with authentik"

          # password: <path:k8s/data/argocd/code-server#password>
          image:
            tag: 'latest'
          persistence: 
            storageClass: longhorn
          ingress:
            enabled: true
            ingressClassName: "traefik"
            annotations: 
              cert-manager.io/cluster-issuer: cluster-ca-issuer
            hosts:
            - host: code-server.lab.smig.tech
              paths:
              - /
            tls: 
            - secretName: code-server-tls
              hosts:
              - code-server.lab.smig.tech
