apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw
  namespace: argocd
  labels:
    apps: development
    smig: charts
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  sources:
    - repoURL: git.thecodedom.com/smig
      targetRevision: 0.1.0
      chart: excalidraw
      helm:
        valueFiles:
          - $values/apps-values/excalidraw.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values




  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: apps
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
