apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    appType: network
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      targetRevision: 1.22.0
      chart: external-dns
      helm:
        valueFiles:
          - $values/apps-values/external-dns.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values

        
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system

  {{ include "app.syncPolicy.automated" . | nindent 2 }}
