apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    appType: network
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.19.0
    chart: external-dns

    helm:     
      valuesObject:
        registry: noop
        provider:
          name: pihole
          pihole:
            server: http://rpi3-ubuntu.lab.smig.tech
        extraArgs:
          source: service
          source: ingress
          pihole-api-version: 6
          pihole-server: https://rpi3-ubuntu.lab.smig.tech
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true



