apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    appType: network
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.20.0
    chart: external-dns

    helm:     
      valuesObject:
        registry: noop
        provider:
          name: pihole
          pihole:
            server: http://rpi3-ubuntu.lab.smig.tech
        extraArgs:
          source: 
          - service
          - ingress
          - gateway-httproute
          - gateway-tlsroute
          - gateway-tcproute
          - gateway-udproute
          pihole-api-version: 6
          pihole-server: http://rpi3-ubuntu.lab.smig.tech:8080
        rbac:  
          additionalPermissions: 
          - apiGroups: ["gateway.networking.k8s.io"]
            resources: ["gateways","httproutes","tlsroutes","tcproutes","udproutes"] 
            verbs: ["get","watch","list"]
          - apiGroups: [""]
            resources: ["namespaces"] 
            verbs: ["get","watch","list"]

        
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system

  {{ include "app.syncPolicy.automated" . | nindent 2 }}
