apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: floci
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    {{ include "app.notifications" . | nindent 4 }}

spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: ./kustomizations/floci
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: floci
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
