apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
  labels:
    apps: storage
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
  destination:
    namespace: garage
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://git.deuxfleurs.fr/Deuxfleurs/garage
      path: script/helm/garage
      targetRevision: v2.4.1
      helm:
        valueFiles:
          - $values/apps-values/garage.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values
