apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garage
  namespace: argocd
  labels:
    apps: storage
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
  destination:
    namespace: garage
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://git.deuxfleurs.fr/Deuxfleurs/garage
    path: script/helm/garage
    targetRevision: v2.3.0
    helm:
      valuesObject:
        image:
          repository: dxflrs/arm64_garage
        garage:
          replicationFactor: 2
          s3:
            api:
              region: "us-east-2"
              rootDomain: "s3.lab.smig.tech"
        deployment:
          replicaCount: 4
        monitoring:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        persistence:
          meta:
            storageClass: "longhorn"
            size: 100Mi
          data:
            storageClass: "longhorn-noreplicas"
            size: 20Gi
        ingress:
          s3:
            api:
              enabled: true
              className: "traefik"
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
              hosts:
                - host: s3.lab.smig.tech
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - secretName: garage-ingress-cert
                  hosts:
                    - s3.lab.smig.tech
