apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io
    targetRevision: 0.54.0
    chart: gitlab-runner 

    helm:
      values: |
            certsSecretName: certs
            gitlabUrl: https://gitlab.lab.smig.tech:8929
            secrets:
              - name: smigtech-cert
            rbac:
              create: true
              rules:
                - resources: ["configmaps", "pods", "pods/attach", "secrets", "services"]
                  verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
                - apiGroups: [""]
                  resources: ["pods/exec"]
                  verbs: ["create", "patch", "delete"]

            runners:
              secret: gitlab-runner
              name: k8s-runner
              config: |
                    [[runners]]
                      [runners.kubernetes]
                          namespace = "{{.Release.Namespace}}"
                          image = "arm64v8/alpine"
                          privileged = true
                          pull_policy = "if-not-present"
                          helper_image = "gitlab/gitlab-runner-helper:arm64-21da6177"
                      [[runners.kubernetes.volumes.secret]]
                          name = "smigtech-cert"
                          mount_path = "/secrets/smigtech/"


  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner

  syncPolicy:
    syncOptions:
    - CreateNamespace=true