apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-runner
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://charts.gitlab.io
    targetRevision: 0.52.0
    chart: gitlab-runner 

    helm:
      values: |
            certsSecretName: certs
            gitlabUrl: https://gitlab.lab.smig.tech:8929
            rbac:
              create: true
            runners:
              secret: gitlab-runner
              name: k8s-runner
              config: |
                    [[runners]]
                      [runners.kubernetes]
                          namespace = "{{.Release.Namespace}}"
                          image = "alpine"



  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-runner

  syncPolicy:
    syncOptions:
    - CreateNamespace=true