apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
spec:
  project: default
  source:
    repoURL: 'https://smiggiddy.github.io'
    targetRevision: 0.2.9
    chart: heimdall
    helm:
      parameters: 
        - name: "storageClassName"
          value: longhorn
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true


