apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
spec:
  project: default
  source:
    repoURL: 'https://djjudas21.github.io/charts/'
    targetRevision: 8.1.7
    chart: homer
    helm:
        values: |
          configmap:
            config:
              enabled: true
              data:
                config.yml: |
                   externalConfig: "https://smiggiddy.github.io/argo/homer/homer-config.yml"
          ingress:
            main: 
              enabled: true
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
              hosts:
              - host: argocd.lab.smig.tech
                paths:
                - path: /
                  pathType: Prefix
              tls:
              - hosts:
                - homer.lab.smig.tech
                secretName: homer-tls


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true