apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
spec:
  project: default
  source:
  - repoURL: 'https://djjudas21.github.io/charts/'
    targetRevision: 8.1.9
    chart: homer
    helm:
      valueFiles:
      - $values/homer/values.yaml

  - repoURL: 'https://gitea.smigz.com/smiggiddy/argocd-values.git'
    targetRevision: HEAD
    ref: values


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
