apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
spec:
  project: default
  source:
    repoURL: 'https://djjudas21.github.io/charts/'
    targetRevision: 8.1.8
    chart: homer
    helm:
        values: |
          nodeSelector: 
            kubernetes.io/hostname: smig-ca06
          persistence:
            config:
              enabled: true
              mountPath: /www/assets/
              type: hostPath
              hostPath: /opt/homer/assets

          ingress:
            main: 
              enabled: true
              ingressClassName: traefik
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
              hosts:
              - host: homer.lab.smig.tech
                paths:
                - path: /
                  pathType: Prefix
              tls:
              - hosts:
                - homer.lab.smig.tech
                secretName: homer-tls


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true