apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  labels:
    apps: homelab
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    path: kustomizations/home-assistant  # Update with your path
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
