apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: host-tuning
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: ./kustomizations/node-settings
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kube-system
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
