apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  destination: 
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.10.3
    chart: immich
    helm:
      valuesObject:
        valkey:
          enabled: true

        controllers:
          main:
            containers:
              main:
                image:
                  tag: v1.143.1
                env: 
                  DB_HOSTNAME: immich-pg-rw.immich.svc.cluster.local 
                  DB_USERNAME: immich
                  DB_DATABASE_NAME: immich
                  DB_PASSWORD: <path:k8s/data/argocd/immich#password>
        immich:
          persistence:
            library:
              existingClaim: immich

        machine-learning:
          controllers:
            main:
              containers:
                main:
                  image: 
                    tag: v1.143.1-armnn
          persistence:
            cache:
              type: persistentVolumeClaim
              storageClass: longhorn
            fw:
              enabled: true
              type: hostPath
              hostPath: /lib/firmware/mali_csffw.bin
              hostPathType: File
              readOnly: true
            driver:
              enabled: true
              type: hostPath
              hostPath: /usr/lib/libmali.so
              hostPathType: File
              readOnly: true
                  
          resources:
            limits:
              squat.ai/mali: 1
        server:
          controllers:
            main:
              containers:
                main:
                  env:
                    DB_HOSTNAME: immich-pg-rw.immich.svc.cluster.local 
                    DB_USERNAME: immich
                    DB_DATABASE_NAME: immich
                    DB_PASSWORD: <path:k8s/data/argocd/immich#password>
          ingress:
            main:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
              hosts:
                - host: immich.lab.smig.tech
                  paths:
                    - path: "/"
              tls: 
               - secretName: immich-tls
                 hosts:
                 - immich.lab.smig.tech
          resources:
            limits:
              squat.ai/video: 1
              cpu: "4"
              memory: "7Gi"
            requests:
              cpu: "2"
              memory: "4Gi"
            
          persistence:
            driver:
              enabled: true
              type: hostPath
              hostPath: /usr/lib/aarch64-linux-gnu/libmali.so.1
              hostPathType: File
              readOnly: true
            opencl:
              enabled: true
              type: hostPath
              hostPath: /etc/OpenCL
              hostPathType: Directory
              readOnly: true
