apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd

spec:
  destination: 
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.9.0
    chart: immich
    helm:
      valuesObject:
        env:
          DB_HOSTNAME: immich-pg-rw.immich.svc.cluster.local 
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          DB_PASSWORD: <path:k8s/data/argocd/immich#password>
        image:
          tag: v1.125.7
        immich:
          persistence:
            library:
              existingClaim: immich
        redis:
          enabled: true
        postgresql:
          enabled: false
          global:
            postgresql:
              auth:
                password: <path:k8s/data/argocd/immich#password>

        machine-learning:
          image: 
            tag: v1.125.7-armnn
          persistence:
            cache:
              type: pvc
              storageClass: longhorn
            fw:
              enabled: true
              type: hostPath
              hostPath: /lib/firmware/mali_csffw.bin
              hostPathType: File
              readOnly: true
            driver:
              enabled: true
              type: hostPath
              hostPath: /usr/lib/libmali.so
              hostPathType: File
              readOnly: true
                  
          resources:
            limits:
              squat.ai/mali: 1
          #/usr/lib/firmware/arm/mali/arch10.8/mali_csffw.bin
          #/usr/lib/aarch64-linux-gnu/dri/mali-dp_dri.so
        server:
          ingress:
            main:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
              hosts:
                - host: immich.lab.smig.tech
                  paths:
                    - path: "/"
              tls: 
               - secretName: immich-tls
                 hosts:
                 - immich.lab.smig.tech
          resources:
            limits:
              squat.ai/video: 1
              # squat.ai/mali: 1
          persistence:
            driver:
              enabled: true
              type: hostPath
              hostPath: /usr/lib/aarch64-linux-gnu/libmali.so.1
              hostPathType: File
              readOnly: true
