apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  sources:
    - repoURL: 'https://smiggiddy.github.io'
      targetRevision: 0.1.0
      chart: it-tools
      helm:
        valueFiles:
          - $values/apps-values/it-tools.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values




  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: apps
  {{ include "app.syncPolicy.manual" . | nindent 2 }}
