apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: 4.3.22
    chart: jenkins 
    
    helm:
      values: |
        controller:
          persistence:
            storageClass: nfs-client
          ingress:
            enabled: true
            ingressClassName: traefik
            hostName: jenkins.lab.smig.tech
            tls:
             - secretName: heimdall
               hosts:
               - jenkins.lab.smig.tech

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true