apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
     avp.kubernetes.io/path: "k8s/data/argocd/test"

spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: 4.3.22
    chart: jenkins 
    
    helm:
      values: |
        persistence:
          storageClass: nfs-client
        controller:
          ingress:
            enabled: true
            ingressClassName: traefik
            hostName: jenkins.lab.smig.tech
            tls:
             - secretName: heimdall-tls
               hosts:
               - jenkins.lab.smig.tech

          installPlugins:
            - kubernetes:3900.va_dce992317b_4
            - workflow-aggregator:596.v8c21c963d92d
            - git:5.0.0
            - configuration-as-code:1625.v27444588cc3d
          
          JCasC:
            securityRealm:
              github:
                githubWebUri: "https://github.com"
                githubApiUri: "https://api.github.com"
                clientID: "someId"
                clientSecret: "${GITHUB_SECRET}"
                oauthScopes: "read:org,user:email"
  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true