apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
     avp.kubernetes.io/path: "k8s/data/argocd/test"

spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: 4.3.22
    chart: jenkins 
    
    helm:
      values: |
        persistence:
          storageClass: nfs-client
        controller:
          ingress:
            enabled: true
            ingressClassName: traefik
            hostName: jenkins.lab.smig.tech
            tls:
             - secretName: heimdall-tls
               hosts:
               - jenkins.lab.smig.tech

  destination:
    server: https://kubernetes.default.svc
    namespace: <ingress>

  syncPolicy:
    syncOptions:
    - CreateNamespace=true