apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
     avp.kubernetes.io/path: "k8s/data/argocd/test"

spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    targetRevision: 4.3.23
    chart: jenkins 
    
    helm:
      values: |
        persistence:
          storageClass: nfs-client
        controller:
          ingress:
            enabled: true
            ingressClassName: traefik
            hostName: jenkins.lab.smig.tech
            tls:
             - secretName: heimdall-tls
               hosts:
               - jenkins.lab.smig.tech

          installPlugins:
            - kubernetes
            - workflow-aggregator
            - git
            - configuration-as-code
            - gitea
          
          # JCasC:
          #   securityRealm: |-
          #     github:
          #       githubWebUri: "https://github.com"
          #       githubApiUri: "https://api.github.com"
          #       clientID: "someId"
          #       clientSecret: "1234566"
          #       oauthScopes: "read:org,user:email"
  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    syncOptions:
    - CreateNamespace=true