apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
  labels:
    apps: security 
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  project: default
  source:
    repoURL: ghcr.io/kubereboot/charts
    targetRevision: 5.11.0
    chart: kured
    helm:
      valuesObject:
        metrics:
          create: true
          labels:
            release: prometheus
        tolerations: [{"key": "node-role.kubernetes.io/control-plane", "effect": "NoSchedule", "value": "true"}]

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    automated:
      selfHeal: true
      prune: true
