apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    apps: security 
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.6.1
    chart: kyverno

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    automated:
      selfHeal: true
      prune: true
