apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    apps: security 
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.5.2
    chart: kyverno

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
