apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
  labels:
    utilities: kube-system
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  destination:
    namespace: apps
    server: {{ .Values.spec.destination.server }} 
  project: default

  source:
    repoURL: {{ .Values.repoURL }}
    path: ./kustomizations/linkding
    targetRevision: HEAD

  {{ include "app.syncPolicy.automated" . | nindent 2 }}

