apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkding
  namespace: argocd
  labels:
    utilities: kube-system
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc 
  project: default

  source:
    repoURL: https://github.com/smiggiddy/argo
    path: ./linkding
    targetRevision: HEAD

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

