apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-stack
  namespace: argocd
  labels:
    type: cloud
    lab: "true"
spec:
  project: default
  source:
    repoURL: https://localstack.github.io/helm-charts
    targetRevision: 0.6.24
    chart: localstack

    helm:
      valuesObject: 
        extraEnvVars:
          - name: LOCALSTACK_HOST 
            value: "local-stack.lab.smig.tech"
        persistence:
          enabled: true
          storageClass: longhorn
        updateStrategy:
          type: Recreate
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: local-stack.lab.smig.tech
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: 
            - secretName: localstack-tls
              hosts: 
              - local-stack.lab.smig.tech
          annotations:
            cert-manager.io/cluster-issuer: cluster-ca-issuer

  destination:
    server: https://kubernetes.default.svc
    namespace: localstack

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
