apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    utilities: kube-system
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.0 
    chart: loki
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            type: s3
            s3:
              endpoint: s3://smig-zima.lab.smig.tech:9000/buckets/loki
              region: us-east-1
              secretAccessKey: blah-blah-blah
              accessKeyId: blah-blah-lbah
              s3ForcePathStyle: true
              insecure: true
          useTestSchema: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
