apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    utilities: kube-system
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  destination:
    namespace: loki
    server: {{ .Values.spec.destination.server }} 
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 7.3.0 
      chart: loki
      helm:
        valueFiles:
          - $values/apps-values/loki.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values
  {{ include "app.syncPolicy.automated" . | nindent 2 }}

