apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    utilities: kube-system
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: HEAD
    targetRevision: 2.10.1 
    chart: loki-stack
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
