apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    utilities: kube-system
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.34.0 
    chart: loki
    helm:
      valuesObject:
        loki:
          auth_enabled: false
          storage:
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            type: s3
            s3:
              endpoint: smig-zima.lab.smig.tech:9000
              region: us-east-1
              secretAccessKey: <path:k8s/data/argocd/minio#secretAccessKey>
              accessKeyId: <path:k8s/data/argocd/minio#accessKeyId>
              s3ForcePathStyle: true
              insecure: true
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            max_concurrent: 4
        read:
          replicas: 2
          persistence:
            storageClass: longhorn-noreplicas
        write:
          replicas: 2
          persistence:
            storageClass: longhorn-noreplicas
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        backend:
          replicas: 2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

