apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    utilities: kube-system
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.3 
    chart: loki
    helm:
      values: |
        loki:
          auth_enabled: false
          storage:
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            type: s3
            s3:
              endpoint: smig-zima.lab.smig.tech:9000
              region: us-east-1
              secretAccessKey: <path:k8s/data/argocd/minio#secretAccessKey>
              accessKeyId: <path:k8s/data/argocd/minio#accessKeyId>
              s3ForcePathStyle: true
              insecure: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
