apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.10.0
    chart: longhorn
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: traefik
          tls: true
          tlsSecret: longhorn-tls
          host: longhorn.lab.smig.tech
          annotations:
            cert-manager.io/cluster-issuer: cluster-ca-issuer
            external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
        persistence:
          defaultClassReplicaCount: 2
          defaultDataLocality: "best-effort"
        metrics:
          serviceMonitor:
            enabled: true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
