apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    apps: utilities 
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
    #server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.1
    chart: longhorn

    helm:
      values:
        test: <path:k8s/data/argocd/test#ingress>

  syncPolicy:
    syncOptions:
    - CreateNamespace=true