apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    apps: utilities 
spec:
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.1
    chart: longhorn

  syncPolicy:
    syncOptions:
    - CreateNamespace=true