apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.6.1
    chart: longhorn
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: traefik
          tls: true
          tlsSecret: longhorn-tls
          host: longhorn.lab.smig.tech
          annotations:
            cert-manager.io/cluster-issuer: cluster-ca-issuer
        persistence:
          defaultClassReplicaCount: 2


  syncPolicy:
    syncOptions:
    - CreateNamespace=true
