apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-root
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    path: ./kustomizations/mattermost
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
  destination:
    namespace: mattermost
    server: {{ .Values.spec.destination.server }}
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
