apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-operator
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    avp.kubernetes.io/ignore: "true"
    {{ include "app.notifications" . | nindent 4 }}
spec:
  destination:
    namespace: mattermost-operator
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://helm.mattermost.com
    targetRevision: 1.0.5
    chart: mattermost-operator
    helm:
      valuesObject:

  {{ include "app.syncPolicy.manual" . | nindent 2 }}
