apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-operator
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    avp.kubernetes.io/ignore: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  destination:
    namespace: mattermost-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.mattermost.com
    targetRevision: 1.0.4
    chart: mattermost-operator
    helm:
      valuesObject:

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
