apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-root
  namespace: argocd
spec:
  project: default
  source:
    path: './mattermost'
    repoURL: 'https://github.com/smiggiddy/argo'
    targetRevision: HEAD
  destination:
    namespace: mattermost
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  
