apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    avp.kubernetes.io/ignore: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://operator.min.io
    targetRevision: 7.1.1
    chart: operator
    helm:
      valuesObject:
        console:
          ingress:
            enabled: true
            ingressClassName: traefik
            tls:
             - secretName: minio-tls
               hosts:
               - minio.lab.smig.tech
            tlsSecret: minio-tls
            host: minio.lab.smig.tech
            annotations:
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
