apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.min.io
    targetRevision: 5.0.15
    chart: minio
    helm:
      values: |
        existingSecret: 'minio'
        replicas: 4
        drivesPerNode: 4
        persistence:
          size: 4Gi
          storageClass: longhorn
        consoleIngress:
          enabled: true
          ingressClassName: traefik
          tls:
           - secretName: minio-console-tls
             hosts:
             - minio-console.lab.smig.tech
          host: minio-console.lab.smig.tech
          annotations:
            cert-manager.io/cluster-issuer: cluster-ca-issuer
        ingress:
          enabled: true
          ingressClassName: traefik
          tls:
           - secretName: minio-tls
             hosts:
             - minio.lab.smig.tech
          host: minio.lab.smig.tech
          annotations:
            cert-manager.io/cluster-issuer: cluster-ca-issuer

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
