apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
   avp.kubernetes.io/ignore: "true"
spec:
  destination:
    namespace: minio-tenant
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://operator.min.io
    targetRevision: 6.0.4
    chart: tenant
    helm:
      values: |
          tenant:
            configSecret:
              name: smigtech-tenant-secret
              accessKey:
              secretKey: 
              existingSecret: true
            configuration:
              name: smigtech-tenant-secret
            name: smigtech
            pools:
            - size: 20Gi
              name: pool-0
              storageClassName: longhorn-noreplicas
            certificate:
              requestAutoCert: false
            metrics:
              enabled: true
          ingress:
            console:
              enabled: true
              ingressClassName: traefik
              tls:
               - secretName: console-tls
                 hosts:
                 - minio-console.lab.smig.tech
              host: minio-console.lab.smig.tech
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
            api:
              enabled: true
              ingressClassName: traefik
              tls:
               - secretName: api-tls
                 hosts:
                 - minio-api.lab.smig.tech
              host: minio-api.lab.smig.tech
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
                traefik.ingress.kubernetes.io/router.entrypoints: websecure

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
