apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  labels:
    apps: homelab 
  annotations:
     avp.kubernetes.io/path: "k8s/data/argocd/test"

spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 7.0.0
    chart: nextcloud
    
    helm:
      valuesObject:
          resources: 
            limits:
             cpu: 200m
             memory: 256Mi
            requests:
             cpu: 100m
             memory: 128Mi
          metrics:
            enabled: true
            
          rbac:
            enabled: true
          image:
            flavor: fpm
          nginx:
            enabled: true
            # config:
            #   custom: |
            #     types {
            #         text/javascript js mjs;
            #       }
          phpClientHttpsFix:
            enabled: false 
            protocol: https
          redis:
            global:
              storageClass: "local-path"
            enabled: true
            auth:
              existingSecret: nextcloud-db
              existingSecretPasswordKey: user-db-password
            image:
              registry: docker.io
              repository: bitnami/redis
              tag: 7.0.12-debian-11-r13
              digest: ""
            master:
              resourcesPreset: "micro"
              persistence:
                size: 1Gi
            replica:
              resourcesPreset: "micro"
              persistence:
                size: 1Gi
          cronjob:
            enabled: true
          persistence:
            enabled: true
            storageClass: longhorn
            size: 20Gi
          externalDatabase:
            enabled: true
            type: postgresql
            user: smigs-cloud
            existingSecret:
              enabled: true
              secretName: nextcloud-db
              usernameKey: db-username
              passwordKey: user-db-password
          postgresql:
            image:
              registry: docker.io
              repository: bitnami/postgresql
              tag: 15.3.0-debian-11-r75
              digest: ""
              pullPolicy: IfNotPresent
              pullSecrets: []
              debug: false
            primary:
              resourcesPreset: "micro"
              persistence:
                enabled: true
                storageClass: longhorn
            enabled: true
            global:
              postgresql:
                auth:
                  username: smigs-cloud
                  existingSecret: nextcloud-db
                  secretKeys:
                    username: db-username
                    adminPasswordKey: db-password
                    userPasswordKey: user-db-password
                    replicationPasswordKey: replication-pw-key
          internalDatabase:
            enabled: false
          nextcloud:
            configs:
              trusted_domains.config.php: |-
                  <?php
                  $CONFIG = [
                  'trusted_domains' =>
                    array (
                      0 => 'localhost',
                      1 => 'cloud.lab.smig.tech',
                      2 => 'cloud.vpn.thecodedom.com'
                      )
                    ];
            host: cloud.lab.smig.tech
            existingSecret:
              enabled: true
              secretName: nextcloud-db
              usernameKey: nextcloud-username
              passwordKey: nextcloud-password
            extraSidecarContainers:
              - name: ts-sidecar
                imagePullPolicy: Always
                image: "ghcr.io/tailscale/tailscale:latest"
                env:
                - name: TS_HOSTNAME
                  value: cloud
                - name: TS_KUBE_SECRET
                  value: tailscale-auth-nextcloud
                - name: TS_USERSPACE
                  value: "false"
                - name: TS_EXTRA_ARGS
                  valueFrom:
                    secretKeyRef:
                      name: tailscale-auth-nextcloud
                      key: extra_args
                      optional: true
                - name: TS_AUTHKEY
                  valueFrom:
                    secretKeyRef:
                      name: tailscale-auth-nextcloud
                      key: TS_AUTHKEY
                      optional: true
                securityContext:
                  capabilities:
                    add:
                    - NET_ADMIN
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-middleware@kubernetescrd,nextcloud-nextcloud-middleware-sts@kubernetescrd

            enabled: true
            className: traefik
            tls:
             - secretName: cloud-tls
               hosts:
               - cloud.lab.smig.tech
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
