apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  labels:
    apps: homelab 
  annotations:
    avp.kubernetes.io/path: "k8s/data/argocd/test"
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua

spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 8.8.1
    chart: nextcloud
    
    helm:
      valuesObject:
          resources: 
            limits:
             cpu: 1000m
             memory: 768Mi
            requests:
             cpu: 500m
             memory: 256Mi
          metrics:
            enabled: true
            
          rbac:
            enabled: true
          image:
            flavor: fpm
          nginx:
            enabled: true
            config:
              headers:
                "Strict-Transport-Security": "max-age=15552000; includeSubDomains; preload;"
          phpClientHttpsFix:
            enabled: false 
            protocol: https
          redis:
            enabled: false
          cronjob:
            enabled: true
          persistence:
            enabled: true
            storageClass: longhorn
            size: 20Gi
          externalDatabase:
            enabled: true
            host: "nextcloud-pg-rw:5432"
            type: postgresql
            database: app
            existingSecret:
              enabled: true
              secretName: nextcloud-pg-app
              usernameKey: username
              passwordKey: password
          internalDatabase:
            enabled: false
          postgresql:
            enabled: false
          nextcloud:
            defaultConfigs:
              .htaccess: false
              apache-pretty-urls.config.php: false
              swift.config.php: false
            configs:
              logging.config.php: |-
                <?php
                $CONFIG = array (
                  'log_type' => 'file',
                  'logfile' => 'nextcloud.log',
                  'loglevel' => 0,
                  'logdateformat' => 'F d, Y H:i:s'
                  );
              trusted_domains.config.php: |-
                  <?php
                  $CONFIG = [
                  'trusted_domains' =>
                    array (
                      0 => 'localhost',
                      1 => 'cloud.lab.smig.tech',
                      2 => 'cloud.vpn.thecodedom.com'
                      )
                    ];
            host: cloud.lab.smig.tech
            existingSecret:
              enabled: true
              secretName: nextcloud-db
              usernameKey: nextcloud-username
              passwordKey: nextcloud-password
            extraSidecarContainers:
              - name: ts-sidecar
                imagePullPolicy: Always
                image: "ghcr.io/tailscale/tailscale:latest@sha256:4a0aaacee6f28e724c1f80c986e5776c9c979d8f7e19274c2cae2d495cc8d625"
                resources:
                  limits:
                    squat.ai/tun: "1"
                  requests:
                    squat.ai/tun: "1"
                env:
                - name: TS_HOSTNAME
                  value: cloud
                - name: TS_KUBE_SECRET
                  value: tailscale-auth-nextcloud
                - name: TS_USERSPACE
                  value: "false"
                - name: TS_EXTRA_ARGS
                  valueFrom:
                    secretKeyRef:
                      name: tailscale-auth-nextcloud
                      key: extra_args
                      optional: true
                - name: TS_AUTHKEY
                  valueFrom:
                    secretKeyRef:
                      name: tailscale-auth-nextcloud
                      key: TS_AUTHKEY
                      optional: true
                securityContext:
                  capabilities:
                    add:
                    - NET_ADMIN
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-middleware@kubernetescrd,nextcloud-nextcloud-middleware-sts@kubernetescrd
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."

            enabled: true
            className: traefik
            tls:
             - secretName: cloud-tls
               hosts:
               - cloud.lab.smig.tech
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
