apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-redis
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    
spec:
  project: default
  source:
    path: './redis/overlays/nextcloud'
    repoURL: 'https://github.com/smiggiddy/argo'
    targetRevision: HEAD
  destination:
    namespace: nextcloud
    server: 'https://kubernetes.default.svc'
