apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  labels:
    apps: homelab 
  annotations:
    avp.kubernetes.io/path: "k8s/data/argocd/test"
    {{ include "app.notifications" . | nindent 4 }}

spec:
  project: default
  sources:
    - repoURL: https://nextcloud.github.io/helm/
      targetRevision: 9.2.6
      chart: nextcloud
      helm:
        valueFiles:
          - $values/apps-values/nextcloud.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nextcloud
  {{ include "app.syncPolicy.manual" . | nindent 2 }}
