apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  labels:
    apps: homelab 
  annotations:
     avp.kubernetes.io/path: "k8s/data/argocd/test"

spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: 3.5.19
    chart: nextcloud
    
    helm:
      values: |
          persistence:
            enabled: true
            storageClass: longhorn
          externalDatabase:
            enabled: true
            type: postgresql
            existingSecret:
              enabled: true
              secretName: nextcloud-db
              usernameKey: db-username
              passwordKey: db-password
          postgresql:
            image:
              registry: docker.io
              repository: bitnami/postgresql
              tag: 15.3.0-debian-11-r75
              digest: ""
              ## Specify a imagePullPolicy
              ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
              ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
              ##
              pullPolicy: IfNotPresent
              ## Optionally specify an array of imagePullSecrets.
              ## Secrets must be manually created in the namespace.
              ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
              ## Example:
              ## pullSecrets:
              ##   - myRegistryKeySecretName
              ##
              pullSecrets: []
              ## Set to true if you would like to see extra information on logs
              ##
              debug: false
            primary:
              persistence:
                enabled: true
                storageClass: longhorn
            enabled: true
            global:
              postgresql:
                auth:
                  existingSecret: nextcloud-db
                  secretKeys:
                    adminPasswordKey: db-password
                    userPasswordKey: user-db-password
                    replicationPasswordKey: replication-pw-key
          internalDatabase:
            enabled: false
          nextcloud:
            host: cloud.lab.smig.tech
            existingSecret:
              enabled: true
              secretName: nextcloud-db
              usernameKey: nextcloud-username
              passwordKey: nextcloud-password
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            enabled: true
            ingressClassName: traefik
            hostName: cloud.lab.smig.tech
            tls:
             - secretName: cloud-tls
               hosts:
               - cloud.lab.smig.tech
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nextcloud
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
