apiVersion: v1
stringData:
  db-password: <db-password>
  user-db-password: <user-db-password>
  replication-pw-key: <replication-pw-key>
  db-username: <db-username>
  nextcloud-username: <nextcloud-username>
  nextcloud-password: <nextcloud-password>
kind: Secret
metadata:
  name: nextcloud-db
  namespace: nextcloud
  annotations:
    avp.kubernetes.io/path: "k8s/data/argocd/nextcloud-db"
type: Opaque
