apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    chart: nfs-subdir-external-provisioner
    helm:
      parameters:
        - name: nfs.server
          value: smigs-nas.lab.smig.tech 
        - name: nfs.path
          value: /volume1/kubernetes
     

  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-stuff

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
