apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    
spec:
  project: default
  source:
    repoURL: https://github.com/smiggiddy/argo
    path: charts/nfs-subdir-external-provisioner
    targetRevision: HEAD
    helm:
      parameters:
        - name: nfs.server
          value: smigs-nas.lab.smig.tech 
        - name: nfs.path
          value: /volume1/kubernetes
        - name: storageClass.defaultClass
          value: "false"
      values: |
            nfs:
              mountOptions:
                - vers=4.1
                - proto=tcp
                - rsize=1048576
                - wsize=1048576
                - timeo=600
            storageClassName: nfs-client 

  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-stuff

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
