apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  labels:
    apps: llm
spec:
  project: default
  source:
    repoURL: https://helm.openwebui.com/
    targetRevision: 8.14.0
    chart: open-webui
    helm:
      valuesObject:
          websocket:
            enabled: true
          ollama:
            enabled: false
          databaseUrl: <path:k8s/data/argocd/openwebui#postgresql>

          ingress:
            enabled: true
            className: "traefik"
            annotations: 
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
            host: chat.lab.smig.tech
            tls: true
            existingSecret: open-webui-tls




  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
