apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  labels:
    apps: llm
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  sources:
    - repoURL: https://helm.openwebui.com/
      targetRevision: 16.5.0
      chart: open-webui
      helm:
        valueFiles:
          - $values/apps-values/open-webui.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: apps
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
