apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  labels:
    apps: llm
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  source:
    repoURL: https://helm.openwebui.com/
    targetRevision: 14.2.0
    chart: open-webui
    helm:
      valuesObject:
          websocket:
            enabled: true
          ollama:
            enabled: false
          databaseUrl: <path:k8s/data/argocd/openwebui#postgresql>

          ingress:
            enabled: true
            className: "traefik"
            annotations: 
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
            host: chat.lab.smig.tech
            tls: true
            existingSecret: open-webui-tls




  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: apps
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
