apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  labels:
    utilities: kube-system
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.17.1
    chart: promtail
    helm:
      values: |
        config:
          clients:
          - url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
            tenant_id: 1
          snippets:
            extraScrapeConfigs: |
              # Add an additional scrape config for syslog
              - job_name: journal
                journal:
                  path: /var/log/journal
                  max_age: 12h
                  labels:
                    job: systemd-journal
                relabel_configs:
                  - source_labels:
                      - '__journal__systemd_unit'
                    target_label: 'unit'
                  - source_labels:
                      - '__journal__hostname'
                    target_label: 'hostname'        
        extraVolumes:
          - name: journal
            hostPath:
              path: /var/log/journal
        extraVolumeMounts:
          - name: journal
            mountPath: /var/log/journal
            readOnly: true

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
