apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    

spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 85.4.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/apps-values/prometheus-stack.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring

  {{ include "app.syncPolicy.automated" . | nindent 2 }}

