apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promethues
  namespace: argocd
  labels:
    apps: utilities 

spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 2.44.0
    chart: prometheus 
    
    helm:
      values: |
          server:
            ingress:
                ## If true, Prometheus server Ingress will be created
                ##
                enabled: true

                ## Prometheus server Ingress hostnames
                ## Must be provided if Ingress is enabled
                ##
                hosts:
                - k3s-prom.lab.smig.tech

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true