apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-resources
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    {{ include "app.notifications" . | nindent 4 }}

spec:
  project: default
  source:
    repoURL: https://github.com/smiggiddy/argo.git
    path: charts/prometheus-resources
    targetRevision: HEAD
    
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring

  {{ include "app.syncPolicy.automated" . | nindent 2 }}

