apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    apps: utilities 

spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 22.6.2
    chart: prometheus 
    
    helm:
      values: |
          alertmanager:
            persistence:
              storageClass: nfs-client
              # storageClassName: nfs-client
          server:
            persistentVolume:
              storageClass: nfs-client
              storageClassName: nfs-client
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
              hosts:
              - k3s-prom.lab.smig.tech
              tls:
              - secretName: smigtech-prom-tls
                hosts:
                - k3s-prom.lab.smig.tech

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true