apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    apps: utilities 

spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.7.0
    chart: kube-prometheus-stack
    
    helm:
      values: |
          kubeEtcd:
            endpoints:
              - 192.168.100.52
              - 192.168.100.53
              - 192.168.100.162
          kubeScheduler:
            endpoints:
              - 192.168.100.52
              - 192.168.100.53
              - 192.168.100.162
          kubeControllerManager:
            endpoints:
              - 192.168.100.52
              - 192.168.100.53
              - 192.168.100.162
          grafana:
            persistence:
              type: sts
              storageClassName: longhorn
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: cluster-ca-issuer
              hosts:
              - grafana-k3s.lab.smig.tech
              tls:
              - secretName: smigtech-grafana-tls
                hosts:
                - grafana-k3s.lab.smig.tech

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
