apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
    avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: ./kustomizations/rabbitmq-operator
    kustomize:
      patches:
        - patch: |-
            $patch: delete
            apiVersion: v1
            kind: Namespace
            metadata:
              name: rabbitmq-system


  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system

  {{ include "app.syncPolicy.automated" . | nindent 2 }}
