apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
  labels:
    apps: storage 
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-health-degraded.mattermost: q51n59rsyjnyxexx5faeuuh8ua
    notifications.argoproj.io/subscribe.on-sync-status-unknown.mattermost: q51n59rsyjnyxexx5faeuuh8ua
spec:
  destination:
    namespace: rustfs
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/smiggiddy/argo.git
    path: charts/rustfs
    targetRevision: HEAD
    helm:
      valuesObject:
          secret:
            create: false
            existingSecret: "deez"
          podAnnotations:
             vault.hashicorp.com/agent-inject: "true"
             vault.hashicorp.com/role: "rustfs"
             vault.hashicorp.com/agent-inject-secret-deez: "k8s/data/argocd/rustfs"
             vault.hashicorp.com/agent-inject-template-deez: |
                {{- with secret "k8s/data/argocd/rustfs" -}}
                export RUSTFS_ACCESS_KEY="{{ .Data.data.access_key }}"
                export RUSTFS_SECRET_KEY="{{ .Data.data.secret_key }}"
                {{- end }}
          ingress:
            enabled: true
            className: "traefik"
            annotations:
              traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
              traefik.ingress.kubernetes.io/service.sticky.cookie.httponly: "true"
              traefik.ingress.kubernetes.io/service.sticky.cookie.name: rustfs
              traefik.ingress.kubernetes.io/service.sticky.cookie.samesite: none
              traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
            tls:
              enabled: true
              certManager:
                enabled: true
            hosts: 
              - host: s3.lab.smig.tech
                paths:
                - path:  "/"
                  pathType: "ImplementationSpecific"
          storageclass:
            name: longhorn-noreplicas
            dataStorageSize: 1Gi

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
