apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
  labels:
    apps: utilities
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
    avp.kubernetes.io/ignore: "true"
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: HEAD
    path: ./kustomizations/searxng
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ai
  {{ include "app.syncPolicy.automated" . | nindent 2 }}
