apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
spec:
  project: default
  source:
    repoURL: 'https://smiggiddy.github.io'
    targetRevision: 0.1.1
    chart: stirling-pdf
    helm:
        valuesObject:
          image:
            name: froodle/s-pdf
            tag: 0.46.2
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            hosts:
            - host: stirling-pdf.lab.smig.tech
              paths:
              - path: /
                pathType: Prefix
            tls:
            - hosts:
              - stirling-pdf.lab.smig.tech
              secretName: stirling-pdf-tls


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
