apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
spec:
  project: default
  source:
    repoURL: 'https://smiggiddy.github.io'
    targetRevision: 0.0.18
    chart: uptime-kuma
    helm:
      parameters: 
        - name: "storageClassName"
          value: longhorn
        - name: "storageSize"
          value: 2Gi
        - name: "image.tag"
          value: "1.23.16"

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true


