apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  labels:
    apps: utilities 
    smig: charts
spec:
  project: default
  source:
    repoURL: 'https://smiggiddy.github.io'
    targetRevision: 0.0.20
    chart: uptime-kuma
    helm:
      parameters: 
        - name: "storageClassName"
          value: longhorn
        - name: "storageSize"
          value: 3Gi
        - name: "image.tag"
          value: "1.23.16"
        - name: "tailscale.authSecretName"
          value: "tailscale-auth"
      valuesObject:
        ingress:
          enabled: true
          className: "traefik"
          annotations: 
            cert-manager.io/cluster-issuer: cluster-ca-issuer
            external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
          hosts:
            - host: up-k.lab.smig.tech
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: uptime-kuma-tls
              hosts:
                - up-k.lab.smig.tech


  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true


