apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.24.1
    chart: vault 

    helm:
      parameters:
        - name: server.dataStorage.storageClass
          value: nfs-client


  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle