apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    apps: utilities 
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.31.0
    chart: vault 

    helm:
      parameters:
        - name: server.dataStorage.storageClass
          value: longhorn
      valuesObject:
        server:
          ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              cert-manager.io/cluster-issuer: cluster-ca-issuer
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              external-dns.alpha.kubernetes.io/target: "k3s.lab.smig.tech."
            hosts:
            - host: https://vault.lab.smig.tech
            tls:
            - secretName: vault-tls 
              hosts: 
              - https://vault.lab.smig.tech


  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
