apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    apps: utilities 
  annotations:
    {{ include "app.notifications" . | nindent 4 }}
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.34.1
      chart: vault 
      helm:
        parameters:
          - name: server.dataStorage.storageClass
            value: longhorn
        valueFiles:
          - $values/apps-values/vault.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: HEAD
      ref: values


  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: vault

  {{ include "app.syncPolicy.manual" . | nindent 2 }}

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
