resources:
  - ./deployment.yaml
  - ./ingress.yaml
  - ./service.yaml

images:
  - name: itzcrazykns1337/vane
    newTag: slim-latest@sha256:541d795d952104be213e7d116e4bb853b9fe35fb8b5a2897c7e2f7e50a6e166e
