apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: linkding
  name: linkding
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linkding
    spec:
      containers:
      - image: sissbruecker/linkding:1.36.0
        name: linkding
        ports:
          - containerPort: 9090
            name: linkding-web
        volumeMounts:
        - mountPath: "/etc/linkding/data"
          name: data
        env:
        - name: LD_SUPERUSER_NAME
          valueFrom:
            secretKeyRef:
              name: linkding-secret 
              key: admin-user

        - name: LD_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkding-secret 
              key: admin-password

        resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: linkding-pvc
status: {}
