apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: linkding
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
