apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment-api.yaml
  - ./deployment-deriver.yaml
  - ./service.yaml
  - ./ingress.yaml
images:
  - name: ghcr.io/plastic-labs/honcho
    newTag: v3.2.2@sha256:c74955d6dbea6dda42c2dd9dd13dea726fcba36ba5c0b6bae4867f7ed762896d
configMapGenerator:
  - name: honcho-config
    envs:
      - ./configmap.yaml
