apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment-api.yaml
  - ./deployment-deriver.yaml
  - ./service.yaml
  - ./ingress.yaml
images:
  - name: ghcr.io/plastic-labs/honcho
    newTag: v3.2.1@sha256:a6bf2f03d47d91281521830ba2a32710a60bde207c37c8f2049fd1ac7619c6d9
configMapGenerator:
  - name: honcho-config
    envs:
      - ./configmap.yaml
