apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment-api.yaml
  - ./deployment-deriver.yaml
  - ./service.yaml
  - ./ingress.yaml
images:
  - name: ghcr.io/plastic-labs/honcho
    newTag: v3.1.0@sha256:b73a8015f9e3ee51525e5b5cb238a915aa47de5107593d81b892213322fa369d
configMapGenerator:
  - name: honcho-config
    envs:
      - ./configmap.yaml
