apiVersion: v1
kind: Service
metadata:
  name: honcho
  labels:
    app: honcho
spec:
  type: ClusterIP
  selector:
    app: honcho
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
