apiVersion: v1
stringData:
  client_id: <path:k8s/data/argocd/code-server#client_id>
  client_secret: <path:k8s/data/argocd/code-server#client_secret>
kind: Secret
metadata:
  name: code-server-oidc
  namespace: apps
type: Opaque
