apiVersion: v1
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: <path:k8s/data/argocd/authentik-grafana#clientId>
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: <path:k8s/data/argocd/authentik-grafana#clientSecret>
  THEMETHOD_PG_PASSWORD: <path:k8s/data/argocd/the-method#password>
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
