apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: smigtech
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  image: docker.io/smiggiddy/mattermost
  imagePullPolicy: Always
  version: 11.1.1
  replicas: 1
  mattermostEnv:
    - name: MM_SERVICESETTINGS_SITEURL
      value: "https://mattermost.thecodedom.com"
    - name: MM_EMAILSETTINGS_SMTPSERVER
      value: "192.168.101.49"
    - name: MM_EMAILSETTINGS_SMTPPORT
      value: "25"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "false"
    - name: MM_FILESETTINGS_AMAZONS3S3SIGNATUREVERSION
      value: "s3v4"
    - name: MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLEPOSTUSERNAMEOVERRIDE
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLEPOSTICONOVERRIDE
      value: "true"
    - name: MM_TEAMSETTINGS_TEAMMATENAMEDISPLAY
      value: "nickname_full_name"
  ingress:
    enabled: false
  database:
    external:
      secret: mm-db-credentials
  fileStore:
    external:
      url: minio.minio-tenant.svc.cluster.local:80
      bucket: mattermost
      secret: file-store-credentials
