apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: smigtech
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  image: docker.io/smiggiddy/mattermost
  imagePullPolicy: IfNotPresent
  version: 11.1.1
  replicas: 1
  mattermostEnv:
    - name: MM_SERVICESETTINGS_SITEURL
      value: https://mattermost.thecodedom.com
    - name: MM_EMAILSETTINGS_SMTPSERVER
      value: "192.168.101.49"
    - name: MM_EMAILSETTINGS_SMTPPORT
      value: "25"
  ingress:
    enabled: false
  database:
    external:
      secret: mm-db-credentials
  fileStore:
    external:
      url: minio.minio-tenant.svc.cluster.local
      bucket: mattermost
      secret: file-store-credentials
