apiVersion: v1
data:
  admin_user: <admin_user>
  admin_password: <admin_password>
kind: Secret
metadata:
  name: awx_admin
  namespace: awx
  annotations:
    avp.kubernetes.io/path: "k8s/data/awx/config"
type: Opaque
