apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opengym-media
  labels:
    app: opengym-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
